### ISSUE TITLE
The type or namespace name 'IWebProxy' could not be found.

### ISSUE THREAD

**Issue by kenany** [rzhw/CloudAppSharp#2]
When attempting to compile CloudAppMain.cs (in Visual Studio 2010), I get the error shown in the title. When I search "IWebProxy" in the ObjectBrowser, I do in fact find it in System.Net, which is already referenced.

**Comment by rzhw** [comment]
Thats... strange. [MSDN](http://msdn.microsoft.com/en-us/library/system.net.iwebproxy%28v=VS.90%29.aspx) says `IWebProxy` is in System.dll, but even so, it should be referenced.

**Comment by kenany** [comment]
I might have found the problem. Looks like IWebProxy (and many other proxy related stuff) isn't available for Windows Phone development (did I mention I was working with WP7 tools? lol).

**Comment by rzhw** [comment]
Oh, okay, haha. Good luck with the project... I wish I had a WP7 phone :P
